### PR TITLE
Laravel 9 support

### PR DESCRIPTION
**Pull request by media253**
Support for Laravel 9

### CODE REVIEW

**Comment by media253** [comment]
@LeoColomb Ah, correct. Done!

**Comment by superbiche** [comment]
@lepikhinb hi, any chance to see this PR merged soon? 
I made a ModelGenerator that supports generating proper types for Enum casts, would love to make a PR for it but this one needs to be merged prior beforehand.  
Thanks

**Comment by robmeijerink** [comment]
@superbiche would be great to see proper enum support!
Thanks

**Comment by superbiche** [comment]
@robmeijerink I will publish a PR in a few days after I've shipped the project I'm working on, but it works. 
For now I managed to have Enum support for Enum casts (not ENUM tables, it must be a model enum cast), and optionally generate the corresponding TS `enum` in another file (a `.ts` file without a namespace so enums are available at runtime).  
Also it will add support for new `Attribute`-based getters.

**Comment by superbiche** [comment]
@robmeijerink see #14 - still a rough draft but a working one. Would love to get your feedback!

**Pull request merged**
